# Solving Lienar Systems Three Ways
___

We are going to solve linear systems in three ways using Numpy and Scipy functions.

In [33]:
import numpy as np
from scipy.linalg import lu

We are solving systems of the form $Ax = b$ where $A$ is a square matrix and $x$ and $b$ are vectors.

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [35]:
b = np.array([1, 2, 3])

In [36]:
# easiest way to solve this system using numpy
x = np.linalg.solve(A, b)
x

array([-0.33333333,  0.66666667,  0.        ])

In [37]:
# check to see that the solution is correct
A.dot(x)
# A@x would also work

array([1., 2., 3.])

In [47]:
A_inv = np.linalg.inv(A)

In [49]:
x2 = A_inv.dot(b)
x2.round(6)

array([-0.333333,  0.666667, -0.      ])

the solution checks out!

The final method of solving linear systems uses the LU factorization of a matrix.

In [62]:
# use lu
P, L, U = lu(A)
P, L, U

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.14285714, 1.        , 0.        ],
        [0.57142857, 0.5       , 1.        ]]),
 array([[7.        , 8.        , 8.        ],
        [0.        , 0.85714286, 1.85714286],
        [0.        , 0.        , 0.5       ]]))

In [61]:
np.linalg.inv(P).dot(A)

array([[7., 8., 8.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [58]:
L.dot(U)

array([[7., 8., 8.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [59]:
P.dot(L.dot(U))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 8.]])

In [64]:
c = np.linalg.solve(L, np.linalg.inv(P).dot(b))

In [65]:
c

array([3.        , 0.57142857, 0.        ])

In [66]:
x3 = np.linalg.solve(U, c)

In [67]:
x3

array([-0.33333333,  0.66666667,  0.        ])

In [ ]:
# the full lu solve method in a function (if P is I, then solve Lc=b first, else Lc=P^-1b)

def lu_solve(A, b):
    P, L, U = lu(A)
    c = np.linalg.solve(L, np.linalg.inv(P).dot(b))
    x = np.linalg.solve(U, c)
    return x